# Generated by Django 3.0.6 on 2020-05-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=100, verbose_name='Projeto')),
                ('descricao', models.TextField(max_length=1000, verbose_name='Descrição')),
                ('tecnologias', models.CharField(max_length=50, verbose_name='Tecnologias')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='Enderço do Site')),
                ('codigo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço do Codigo')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(upload_to='', verbose_name='Carregar Imagem')),
            ],
            options={
                'db_table': 'projetos',
            },
        ),
    ]
