# Generated by Django 3.1.12 on 2021-09-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologia', models.CharField(max_length=50, verbose_name='Tecnologias')),
            ],
            options={
                'db_table': 'tecnolgias',
            },
        ),
        migrations.RemoveField(
            model_name='projetos',
            name='tecnologias',
        ),
        migrations.AddField(
            model_name='projetos',
            name='tecnologias',
            field=models.ManyToManyField(to='portfolio.Tecnologias', verbose_name='Tecnologias'),
        ),
    ]
